import { getRequestLocale } from "intl-t/next"
import type { Metadata } from "next"
import { JetBrains_Mono } from "next/font/google"
import "./globals.css"
import { Providers } from "@/components/providers"
import { Translation } from "@/i18n/translation"

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const locale = await getRequestLocale() as typeof Translation.locale
  return (
    <html lang={locale}>
      <body className={`${jetbrainsMono.variable} antialiased`}>
        <Translation locale={locale}>
          <Providers>{children}</Providers>
        </Translation>
      </body>
    </html>
  )
}
